# Generated by Django 4.1 on 2022-12-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="found_child_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_name", models.CharField(max_length=100)),
                ("child_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(blank=True, max_length=12)),
                ("address", models.TextField()),
                ("email", models.CharField(blank=True, max_length=254)),
                ("img", models.ImageField(upload_to="photos")),
            ],
        ),
    ]
