# Generated by Django 4.1 on 2022-12-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="found_child_data",
            name="email",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="found_child_data",
            name="phone_number",
            field=models.CharField(max_length=12),
        ),
    ]
