# Generated by Django 4.1 on 2022-12-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_found_child_data_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="missing_child_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_name", models.CharField(max_length=100)),
                ("child_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=12)),
                ("address", models.CharField(max_length=100)),
                ("email", models.CharField(blank=True, max_length=254, null=True)),
                ("img", models.ImageField(upload_to="photos")),
            ],
        ),
    ]
