# Generated by Django 4.1 on 2022-12-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_missing_child_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="found_child_data",
            name="img",
            field=models.ImageField(upload_to="found_photos"),
        ),
        migrations.AlterField(
            model_name="missing_child_data",
            name="img",
            field=models.ImageField(upload_to="missing_photos"),
        ),
    ]
